#ifndef CONNECTION_TYPES_H
#define CONNECTION_TYPES_H

#define CONN_TYPE_EMULATION 0
#define CONN_TYPE_SERVO180 0
#define CONN_TYPE_SERVO360 0
#define CONN_TYPE_PIN_DIRECT 0
#define CONN_TYPE_PIN_TOGGLE 0


#endif